image: "python:3.9"

default:
  tags:
    - docker

stages:
  - test

variables:
  CODECOV_TOKEN: "3a640655-0921-4aaa-9f17-87870da992b9"

before_script:
  - pip install .
  - pip install pytest pytest-cov

test: 
  stage: test
  script:
    - make test
    - bash <(curl -s https://codecov.io/bash)
  only:
    refs:
      - master
    changes:
      - prettypy
