image: "python:3.8"

default:
  tags:
    - docker

stages:
  - test

variables:
  CODECOV_TOKEN: "3a640655-0921-4aaa-9f17-87870da992b9"

before_script:
  - pip install -r requirements.txt

test: 
  stage: test
  script:
    - make test
  only:
    refs:
      - master
